"""add tasks and acceptances

Revision ID: 70e0be6f4e19
Revises: ca9c8210c1d3
Create Date: 2026-03-27 17:31:34.009574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70e0be6f4e19'
down_revision: Union[str, Sequence[str], None] = 'ca9c8210c1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poster_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('task_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('suggested_price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['task_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id')
    )
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_poster_id'), 'tasks', ['poster_id'], unique=False)
    op.create_table('task_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tasker_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'CANCELLED', name='acceptance_status'), nullable=False),
    sa.Column('acknowledgement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tasker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'tasker_id', name='uq_task_acceptances_task_tasker')
    )
    op.create_index(op.f('ix_task_acceptances_task_id'), 'task_acceptances', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_acceptances_tasker_id'), 'task_acceptances', ['tasker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_acceptances_tasker_id'), table_name='task_acceptances')
    op.drop_index(op.f('ix_task_acceptances_task_id'), table_name='task_acceptances')
    op.drop_table('task_acceptances')
    op.drop_index(op.f('ix_tasks_poster_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
