"""add evidence verification escrow disputes

Revision ID: f2c4fb9f47f7
Revises: 70e0be6f4e19
Create Date: 2026-03-27 17:40:25.642843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2c4fb9f47f7'
down_revision: Union[str, Sequence[str], None] = '70e0be6f4e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('opened_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='dispute_status'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_opened_by_id'), 'disputes', ['opened_by_id'], unique=False)
    op.create_index(op.f('ix_disputes_task_id'), 'disputes', ['task_id'], unique=False)
    op.create_table('escrow_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('HELD', 'RELEASE_ELIGIBLE', 'RELEASED', 'DISPUTE_OPENED', 'CANCELLED', name='escrow_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('evidence_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('before_image_url', sa.String(length=1000), nullable=True),
    sa.Column('after_image_url', sa.String(length=1000), nullable=True),
    sa.Column('evidence_video_url', sa.String(length=1000), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_uploads_task_id'), 'evidence_uploads', ['task_id'], unique=False)
    op.create_index(op.f('ix_evidence_uploads_uploaded_by_id'), 'evidence_uploads', ['uploaded_by_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'LOW_CONFIDENCE', 'FAIL', name='verification_status'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_task_id'), 'verification_results', ['task_id'], unique=False)
    op.create_table('dispute_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_events_dispute_id'), 'dispute_events', ['dispute_id'], unique=False)
    op.create_table('escrow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escrow_payment_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HELD', 'VERIFICATION_PASSED', 'VERIFICATION_FAILED', 'RELEASE_ELIGIBLE', 'RELEASED', 'DISPUTE_OPENED', 'CANCELLED', name='escrow_event_type'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escrow_payment_id'], ['escrow_payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_events_escrow_payment_id'), 'escrow_events', ['escrow_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escrow_events_escrow_payment_id'), table_name='escrow_events')
    op.drop_table('escrow_events')
    op.drop_index(op.f('ix_dispute_events_dispute_id'), table_name='dispute_events')
    op.drop_table('dispute_events')
    op.drop_index(op.f('ix_verification_results_task_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_evidence_uploads_uploaded_by_id'), table_name='evidence_uploads')
    op.drop_index(op.f('ix_evidence_uploads_task_id'), table_name='evidence_uploads')
    op.drop_table('evidence_uploads')
    op.drop_table('escrow_payments')
    op.drop_index(op.f('ix_disputes_task_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_opened_by_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
